{
 "title": "VCF License Reporting",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "VCF CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "vcf",
     "rawSql": "SELECT\n  `Usage Hour`,\n  SUM(`Quantity`) AS `VCF CPU Cores`\nFROM license_cpu_core_usage\nGROUP BY `Usage Hour`\nORDER BY `Usage Hour`;"
    }
   ]
  },
  {
   "title": "VCF CPU Cores - By Provider",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  l.`Usage Hour` AS time,\n  CONCAT(p.provider_name) AS instance,\n  SUM(l.`Quantity`) AS value\nFROM license_cpu_core_usage l\nJOIN usage_meter u\n  ON u.usage_meter_id = l.`Usage Meter Instance ID`\nJOIN provider p\n  ON p.provider_id = u.provider_id\nGROUP BY\n  time,\n  instance\nORDER BY\n  time;\n"
    }
   ]
  },
  {
   "title": "VCF CPU Cores - By Usage Meter",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  l.`Usage Hour` AS time,\n  CONCAT(p.provider_name, '-', u.usage_meter_name) AS instance,\n  SUM(l.`Quantity`) AS value\nFROM license_cpu_core_usage l\nJOIN usage_meter u\n  ON u.usage_meter_id = l.`Usage Meter Instance ID`\nJOIN provider p\n  ON p.provider_id = u.provider_id\nGROUP BY\n  time,\n  instance\nORDER BY\n  time;\n"
    }
   ]
  }
 ]
}